[package]
name = "chipioindustries/llama"
description = "Luau Library for Immutable Data"
version = "1.3.1"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
include = ["default.project.json", "src"]
exclude = ["**"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
