[package]
name = "chipioindustries/llama"
description = "Luau Library for Immutable Data"
version = "1.1.1"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
include = ["default.project.json", "src"]